<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import seaborn as sns
np.set_printoptions(suppress=True)

In [19]:
raw_df = pd.read_csv('example_data.csv', index_col=0)
raw_df

Cylinders  Displacement  Horsepower  Weight  Acceleration  Model Year  \
9            8         390.0       190.0  3850.0           8.5          70   
25           8         360.0       215.0  4615.0          14.0          70   
28           8         304.0       193.0  4732.0          18.5          70   
31           4         113.0        95.0  2228.0          14.0          71   
33           6         232.0       100.0  2634.0          13.0          71   
..         ...           ...         ...     ...           ...         ...   
369          4         112.0        88.0  2395.0          18.0          82   
375          4         105.0        74.0  1980.0          15.3          82   
382          4         108.0        70.0  2245.0          16.9          82   
384          4          91.0        67.0  1965.0          15.7          82   
396          4         120.0        79.0  2625.0          18.6          82   

     Europe  Japan  USA  
9         0      0    1  
25        0      0    1  
28        0      0    1  
31        0      1    0  
33        0      0    1  
..      ...    ...  ...  
369       0      0    1  
375       1      0    0  
382       0      1    0  
384       0      1    0  
396       0      0    1  

[78 rows x 9 columns]

In [20]:
raw_df.iloc[0]

Cylinders          8.0
Displacement     390.0
Horsepower       190.0
Weight          3850.0
Acceleration       8.5
Model Year        70.0
Europe             0.0
Japan              0.0
USA                1.0
Name: 9, dtype: float64

In [21]:
path = "dnn_model"
model = keras.models.load_model(path) # or tf.saved_model.load(path)
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
normalization (Normalization (None, 9)                 19        
_________________________________________________________________
dense_5 (Dense)              (None, 64)                640       
_________________________________________________________________
dense_6 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 65        
Total params: 4,884
Trainable params: 4,865
Non-trainable params: 19
_________________________________________________________________


In [29]:
model.predict(raw_df[:1].values)

array([[15.818567]], dtype=float32)

In [33]:
raw_df.iloc[0].values

array([   8. ,  390. ,  190. , 3850. ,    8.5,   70. ,    0. ,    0. ,
          1. ])

In [5]:
from flask import Flask
from flask_restful import Resource, Api, reqparse
import pandas as pd
import ast

app = Flask(__name__)
api = Api(app)

In [6]:
class Users(Resource):
    def get(self):
        data = pd.read_csv('example_data.csv', index_col=0)  # read CSV
        data = data.to_dict()  # convert dataframe to dictionary
        return {'data': data}, 200  # return data and 200 OK code
    
class Locations(Resource):
    # methods go here
    pass
    
api.add_resource(Users, '/users')  # '/users' is our entry point for Users
api.add_resource(Locations, '/locations')  # and '/locations' is our entry point for Locations

In [7]:
app.run()  # run our Flask app

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Apr/2021 15:25:21] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [02/Apr/2021 15:26:03] "GET /users HTTP/1.1" 200 -
127.0.0.1 - - [02/Apr/2021 15:28:45] "GET /users HTTP/1.1" 200 -


In [11]:
d = {'Cylinders': 8.0, 'Displacement': 390.0, 'Horsepower': 190.0, 'Weight': 3850.0, 'Acceleration': 8.5, 'Model Year': 70.0, 'Europe': 0.0, 'Japan': 0.0, 'USA': 1.0}
d

{'Cylinders': 8.0,
 'Displacement': 390.0,
 'Horsepower': 190.0,
 'Weight': 3850.0,
 'Acceleration': 8.5,
 'Model Year': 70.0,
 'Europe': 0.0,
 'Japan': 0.0,
 'USA': 1.0}

In [46]:
model.predict(np.array(list(d.values()),ndmin=2, dtype=np.float32))

array([[15.818567]], dtype=float32)

In [ ]:
model.predict([8.00e+00 3.90e+02 1.90e+02 3.85e+03 8.50e+00 7.00e+01 0.00e+00 0.00e+00
 1.00e+00])

In [48]:
list(d.values())

[8.0, 390.0, 190.0, 3850.0, 8.5, 70.0, 0.0, 0.0, 1.0]

In [77]:
r = model.predict(np.array([8.0, 390.0, 190.0, 3850.0, 8.5, 70.0, 0.0, 0.0, 1.0], ndmin=2)).squeeze().tolist()

In [78]:
r

15.818567276000977